// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: data/proto/mailer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link  string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *RegisterEmailRequest) Reset() {
	*x = RegisterEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_mailer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEmailRequest) ProtoMessage() {}

func (x *RegisterEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_mailer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEmailRequest.ProtoReflect.Descriptor instead.
func (*RegisterEmailRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_mailer_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterEmailRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RegisterEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsError bool   `protobuf:"varint,1,opt,name=isError,proto3" json:"isError,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RegisterEmailResponse) Reset() {
	*x = RegisterEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_mailer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEmailResponse) ProtoMessage() {}

func (x *RegisterEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_mailer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEmailResponse.ProtoReflect.Descriptor instead.
func (*RegisterEmailResponse) Descriptor() ([]byte, []int) {
	return file_data_proto_mailer_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterEmailResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *RegisterEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForgotPasswordRequestEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link  string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ForgotPasswordRequestEmail) Reset() {
	*x = ForgotPasswordRequestEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_mailer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForgotPasswordRequestEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequestEmail) ProtoMessage() {}

func (x *ForgotPasswordRequestEmail) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_mailer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequestEmail.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequestEmail) Descriptor() ([]byte, []int) {
	return file_data_proto_mailer_proto_rawDescGZIP(), []int{2}
}

func (x *ForgotPasswordRequestEmail) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ForgotPasswordRequestEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgotPasswordResponseEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsError bool   `protobuf:"varint,1,opt,name=isError,proto3" json:"isError,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ForgotPasswordResponseEmail) Reset() {
	*x = ForgotPasswordResponseEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_mailer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForgotPasswordResponseEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponseEmail) ProtoMessage() {}

func (x *ForgotPasswordResponseEmail) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_mailer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponseEmail.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponseEmail) Descriptor() ([]byte, []int) {
	return file_data_proto_mailer_proto_rawDescGZIP(), []int{3}
}

func (x *ForgotPasswordResponseEmail) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ForgotPasswordResponseEmail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_data_proto_mailer_proto protoreflect.FileDescriptor

var file_data_proto_mailer_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x69,
	0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x65,
	0x72, 0x22, 0x40, 0x0a, 0x14, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x22, 0x4b, 0x0a, 0x15, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69,
	0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x46, 0x0a, 0x1a, 0x66, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x51, 0x0a, 0x1b, 0x66, 0x6f, 0x72, 0x67,
	0x6f, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xd5, 0x01, 0x0a, 0x0d,
	0x4d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a,
	0x1d, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d,
	0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x1b, 0x53,
	0x65, 0x6e, 0x64, 0x46, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x2e, 0x6d, 0x61, 0x69,
	0x6c, 0x65, 0x72, 0x2e, 0x66, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x23,
	0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x66, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_proto_mailer_proto_rawDescOnce sync.Once
	file_data_proto_mailer_proto_rawDescData = file_data_proto_mailer_proto_rawDesc
)

func file_data_proto_mailer_proto_rawDescGZIP() []byte {
	file_data_proto_mailer_proto_rawDescOnce.Do(func() {
		file_data_proto_mailer_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_proto_mailer_proto_rawDescData)
	})
	return file_data_proto_mailer_proto_rawDescData
}

var file_data_proto_mailer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_proto_mailer_proto_goTypes = []interface{}{
	(*RegisterEmailRequest)(nil),        // 0: mailer.registerEmailRequest
	(*RegisterEmailResponse)(nil),       // 1: mailer.registerEmailResponse
	(*ForgotPasswordRequestEmail)(nil),  // 2: mailer.forgotPasswordRequestEmail
	(*ForgotPasswordResponseEmail)(nil), // 3: mailer.forgotPasswordResponseEmail
}
var file_data_proto_mailer_proto_depIdxs = []int32{
	0, // 0: mailer.MailerService.SendRegisterEmailVerification:input_type -> mailer.registerEmailRequest
	2, // 1: mailer.MailerService.SendForgotPasswordLinkEmail:input_type -> mailer.forgotPasswordRequestEmail
	1, // 2: mailer.MailerService.SendRegisterEmailVerification:output_type -> mailer.registerEmailResponse
	3, // 3: mailer.MailerService.SendForgotPasswordLinkEmail:output_type -> mailer.forgotPasswordResponseEmail
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_proto_mailer_proto_init() }
func file_data_proto_mailer_proto_init() {
	if File_data_proto_mailer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_proto_mailer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_mailer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_mailer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForgotPasswordRequestEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_mailer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForgotPasswordResponseEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_proto_mailer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_proto_mailer_proto_goTypes,
		DependencyIndexes: file_data_proto_mailer_proto_depIdxs,
		MessageInfos:      file_data_proto_mailer_proto_msgTypes,
	}.Build()
	File_data_proto_mailer_proto = out.File
	file_data_proto_mailer_proto_rawDesc = nil
	file_data_proto_mailer_proto_goTypes = nil
	file_data_proto_mailer_proto_depIdxs = nil
}
