version: '3'

services:
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    stdin_open: true # docker run -i
    tty: true      
    environment:
      DSN: "host=postgres port=5432 user=gocommmicro password=password dbname=gocommmicro sslmode=disable timezone=UTC connect_timeout=5"

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  
  postgres:
    image: 'postgres:16.0'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: gocommmicro
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gocommmicro
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./db-data/postgres/:/var/lib/postgresql/data/
volumes:
  pgdata: