version: '3'

services:
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=gocommmicro password=password dbname=gocommmicro sslmode=disable timezone=UTC connect_timeout=5"
      TESTDBDSN: "host=postgres port=5432 user=gocommmicro password=password dbname=testdb sslmode=disable timezone=UTC connect_timeout=5"
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  
  mailer-service:
    build:
      context: ./../mailer-service
      dockerfile: ./../mailer-service/mailer-service.dockerfile
    restart: always
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: 'postgres:16.0'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_MULTIPLE_DATABASES: gocommmicro,testdb
      POSTGRES_USER: gocommmicro
      POSTGRES_PASSWORD: password
    volumes:
      - ../project/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      #- ./db-data/postgres/:/var/lib/postgresql/data/
volumes:
  pgdata: